# Generated by Django 6.0.3 on 2026-03-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="level",
            field=models.IntegerField(
                default=7, help_text="Number from 0 to 10 representing proficiency"
            ),
        ),
    ]
